name: wise_bluetooth_print
description: Socket timeout is added to keep socket open for longer for print
  operations for multiple labels. Timeout defaults to 100ms (as original) if no
  timeout value is passed.
version: 0.0.3
homepage: https://github.com/kaanakyalcin/wise_bluetooth_print

environment:
  sdk: ">=2.16.0 <3.3.10"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.wise_bluetooth_print
        pluginClass: WiseBluetoothPrintPlugin
